task:
  name: Tests (linux)
  container:
    image: ubuntu:latest
  script: bash ./pytest.sh

task:
  name: Tests (macOS)
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest
  script: sh ./pytest.sh



