task:
  name: Tests (linux)
  container:
    image: ubuntu:latest
  install_script:
    - apt-get update
    - apt-get -y install python3 python3-venv g++
  test_script: 
    - bash ./pytest.sh


task:
  name: Tests (macOS)
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest
  script: 
    - sh ./pytest.sh



